### ISSUE TITLE
Certifikat Error

### ISSUE THREAD

**Issue by vr6syncro** [kimmknight/raweb#13]
Hello, i installed all follewed the instructions but cant get it to work.
Win2022Server and Win11 Client.

The certificate is available but no connection for the remotedesktop.

The RDP Apps are working only the Startmenue link thing with the ssl is not working.

![image](https://user-images.githubusercontent.com/27892314/235354574-e6a27644-aa9a-40dd-afc1-6bfc2958c20f.png)

**Comment by apathyzen** [comment]
Hello!
I assume that you've encountered the same problem as me, being unable to add a RDS feed via Control Panel.
 
The problem is that the self-signed certificate is issued for your IIS server's %COMPUTERNAME%.
So.
My IIS server hostname is: DESKTOP-DHEEQ30
I need modify default website binding host name to DESKTOP-DHEEQ30.
![image](https://github.com/kimmknight/raweb/assets/32571536/37496fd2-4a9e-48fa-be0e-5d96e60c9d4f)

And then modify the webfeed from clients via https://desktop-dheeq30/webfeed.asp
![image](https://github.com/kimmknight/raweb/assets/32571536/10b12e88-1f8b-4536-9efa-4e7d190df432)

**Comment by kimmknight** [comment]
Thanks @apathyzen !

For anyone who can't read the language in the screenshot, you need to export the self-signed certificate and import it to Trusted Root Certification Authorities on the client.
