### ISSUE TITLE
RDP file gets downloaded

### ISSUE THREAD

**Issue by saurav-biswas** [kimmknight/raweb#2]
When I click on the icon in the browser, it gets downloaded in place of opening the RDP file within the browser.
http://greenapplevpsserver.in/
Please check the link above.

**Comment by MrBrianGale** [comment]
That is by design of your browser.  Files get downloaded when you click on them UNLESS the browser has support for that file extension (such as a PDF).
Otherwise, your web browser will download the file and not "open" it by default.
Depending on your browser, I imagine there may be some addon or setting that allows this behavior to change.

**Comment by kimmknight** [comment]
As MrBrianGale commented, you'll probably need your browser set to automatically open RDP files.

Using the webfeed might be a better option (if your situation allows).
