### ISSUE TITLE
IOS and RDWeb

### ISSUE THREAD

**Issue by Vegas605** [kimmknight/raweb#9]
Is there any plans to make the RDWeb work with IOS? I have been using this on windows with 100% integration, but ipads not so much

**Comment by kimmknight** [comment]
The new RD client apps for IOS, Android and Windows Store versions (v10+) all use a new method to communicate with the RDWeb server. On Android, you can obtain and install an old version of the app as a workaround. I'm not sure if this is possible with IOS.

If I figure out how to implement the new RDWeb communication, I will probably implement it in my newer project, [rdpx](https://github.com/kimmknight/rdpx).

**Comment by Vegas605** [comment]
Awesome, that’s fantastic. I will keep watching the new project

**Comment by JeffreyO** [comment]
That explains my problem. I'm curious to see if this has been implemented but have something to share about my experience with trying to get this to work. 

When trying to setup Windows 10 with RemoteApp, it worked perfectly and Wireshark showed the communication.
When using the Remote Desktop UWP app however and trying to set up a Workspace, it never got past the initial SSL Hello packet and didn't even try to communicate with the server.

I'm starting to wonder if it's because the certificate is self-signed even though it's installed onto the client computer or just an issue with IIS settings.

**Comment by JeffreyO** [comment]
I have resolved the HTTPS problem with a smallstep.com certificate installed to the client computer's machine certificatestore and configured the server with NGINX.

I'm now looking into how to get Workspaces working.

**Comment by kimmknight** [comment]
Hey @JeffreyO, have you checked out [Issue 6](https://github.com/kimmknight/raweb/issues/6)? If not, it might be worth a look as I have documented some of my efforts trying to get workspaces working.

**Comment by kimmknight** [comment]
So, akarl10's update to the ASPX version seems to have fixed this for the Android client! RAWeb can be added as a workspace.

Anyone able to test on IOS or Mac?

**Comment by kimmknight** [comment]
Support for Android/IOS/MacOS clients added in commit 3dd8fab
